config/routes.rb
Huddle::Application.routes.draw do
  resources :status_reports

  resources :projects

  devise_for :users

  root 'welcome#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :status_reports

  def reports_grouped_by_day
    status_reports.by_user_name.group_by(&:status_date)
  end
end

app/models/status_report.rb
class StatusReport < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  before_save :set_status_date

  validate :validate_has_at_least_one_status

  private

  def set_status_date
    self.status_date = Date.today if status_date.nil?
  end

  def validate_has_at_least_one_status
    if today.blank? && yesterday.blank?
      errors[:base] << "Must have at least one status set"
    end
  end

  scope :by_user_name, include: "user",
    order: "users.email ASC",
    conditions: "user_id IS NOT NULL"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  helper_method :current_project

  private

  def current_project
    Project.find(session[:project_id]) rescue Project.last
  end

  def redirect_if_not_current_user(user_id)
    if user_id && user_id != current_user.id
      sign_out(current_user)
      redirect_to new_user_session_path
      return true
    end
    false
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @reports = @project.reports_grouped_by_day
    respond_to do |format|
      format.html # show.html.erb
      format.xml { render xml: @project }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/status_reports_controller.rb
class StatusReportsController < ApplicationController
  before_action :set_status_report, only: [:show, :edit, :update, :destroy]

  # GET /status_reports
  # GET /status_reports.json
  def index
    @status_reports = StatusReport.all
  end

  # GET /status_reports/1
  # GET /status_reports/1.json
  def show
  end

  # GET /status_reports/new
  def new
    @status_report = StatusReport.new
  end

  # GET /status_reports/1/edit
  def edit
  end

  # POST /status_reports
  # POST /status_reports.json
  def create
    redirect_if_not_current_user(params[:status_report][:user_id]) and return
    params[:status_report].merge!(user_id: current_user.id, project_id: current_project.id)
    @status_report = StatusReport.new(status_report_params)

    respond_to do |format|
      if @status_report.save
        format.html { redirect_to @status_report, notice: 'Status report was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status_report }
      else
        format.html { render action: 'new' }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /status_reports/1
  # PATCH/PUT /status_reports/1.json
  def update
    respond_to do |format|
      if @status_report.update(status_report_params)
        format.html { redirect_to @status_report, notice: 'Status report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /status_reports/1
  # DELETE /status_reports/1.json
  def destroy
    @status_report.destroy
    respond_to do |format|
      format.html { redirect_to status_reports_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status_report
      @status_report = StatusReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_report_params
      params.require(:status_report).permit(:project_id, :user_id, :yesterday, :today, :status_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/status_reports_helper.rb
module StatusReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huddle</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<h2>Status Reports for <%= @project.name %></h2>
<% @reports.keys.sort.each do |date| %>
  <div id="<%= date.to_s(:db) %>_day">
    <h3>Reports for <%= date.to_s(:long) %></h3>
    <% @reports[date].each do |report| %>
      <div id="<%= dom_id(report) %>">
        Yesterday I: <%= report.yesterday %>
        Today I will: <%= report.today %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/status_reports/_form.html.erb
<%= form_for(@status_report) do |f| %>
  <% if @status_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status_report.errors.count, "error") %> prohibited this status_report from being saved:</h2>

      <ul>
      <% @status_report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :yesterday %><br>
    <%= f.text_area :yesterday %>
  </div>
  <div class="field">
    <%= f.label :today %><br>
    <%= f.text_area :today %>
  </div>
  <div class="field">
    <%= f.label :status_date %><br>
    <%= f.date_select :status_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/status_reports/edit.html.erb
<h1>Editing status_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @status_report %> |
<%= link_to 'Back', status_reports_path %>

app/views/status_reports/index.html.erb
<h1>Listing status_reports</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>User</th>
      <th>Yesterday</th>
      <th>Today</th>
      <th>Status date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @status_reports.each do |status_report| %>
      <tr>
        <td><%= status_report.project %></td>
        <td><%= status_report.user %></td>
        <td><%= status_report.yesterday %></td>
        <td><%= status_report.today %></td>
        <td><%= status_report.status_date %></td>
        <td><%= link_to 'Show', status_report %></td>
        <td><%= link_to 'Edit', edit_status_report_path(status_report) %></td>
        <td><%= link_to 'Destroy', status_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status report', new_status_report_path %>

app/views/status_reports/new.html.erb
<h1>New status_report</h1>

<%= render 'form' %>

<%= link_to 'Back', status_reports_path %>

app/views/status_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @status_report.project %>
</p>

<p>
  <strong>User:</strong>
  <%= @status_report.user %>
</p>

<p>
  <strong>Yesterday:</strong>
  <%= @status_report.yesterday %>
</p>

<p>
  <strong>Today:</strong>
  <%= @status_report.today %>
</p>

<p>
  <strong>Status date:</strong>
  <%= @status_report.status_date %>
</p>

<%= link_to 'Edit', edit_status_report_path(@status_report) %> |
<%= link_to 'Back', status_reports_path %>